"""add is active in master

Revision ID: 3d8582647905
Revises: f8501a55824e
Create Date: 2026-06-28 09:14:00.380278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8582647905'
down_revision: Union[str, Sequence[str], None] = 'f8501a55824e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'is_active')
    # ### end Alembic commands ###
