"""add phone to master

Revision ID: 7c49ebc5c381
Revises: 5efa2501188a
Create Date: 2026-06-24 11:36:35.421702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c49ebc5c381'
down_revision: Union[str, Sequence[str], None] = '5efa2501188a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_masters_phone'), 'masters', ['phone'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_masters_phone'), table_name='masters')
    op.drop_column('masters', 'phone')
    # ### end Alembic commands ###
