"""add is_active to services

Revision ID: ba47ddbb547c
Revises: 18ee7fe3edca
Create Date: 2026-06-26 14:14:52.787837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba47ddbb547c'
down_revision: Union[str, Sequence[str], None] = '18ee7fe3edca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_active')
    # ### end Alembic commands ###
