"""Add cancel_token to appointment

Revision ID: c2e70d0dfe3b
Revises: 2b3867987220
Create Date: 2026-06-26 09:59:27.575575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e70d0dfe3b'
down_revision: Union[str, Sequence[str], None] = '2b3867987220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancel_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_appointments_cancel_token'), 'appointments', ['cancel_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_cancel_token'), table_name='appointments')
    op.drop_column('appointments', 'cancel_token')
    # ### end Alembic commands ###
