"""add stripe id

Revision ID: d7799d9fda8d
Revises: 3d8582647905
Create Date: 2026-07-01 12:54:36.013909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7799d9fda8d'
down_revision: Union[str, Sequence[str], None] = '3d8582647905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('stripe_payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'stripe_payment_id')
    # ### end Alembic commands ###
